name: Docker Build and Publish

on:
  push:
    branches: [ "master" ]
    paths:
      - 'php8.4-phalcon5.9/**'
      - 'php8.2-phalcon5/**'
      - 'php7.3-phalcon3/**'
      - '.github/workflows/docker-publish.yml'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKERHUB_USERNAME: fvildoso

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push PHP 8.4 Phalcon 5.9 (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./php8.4-phalcon5.9
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:8.4-phalcon5.9.4
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:8.4-phalcon5.9

      - name: Build and push PHP 8.2 Phalcon 5 (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./php8.2-phalcon5
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:8.2.19-phalcon5.7.0-alpine
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:8.2-phalcon5-alpine
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:latest

      - name: Build and push PHP 7.3 Phalcon 3 (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./php7.3-phalcon3
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:7.3.33-phalcon3.4.5-alpine
            ${{ env.DOCKERHUB_USERNAME }}/php-phalcon:7.3-phalcon3-alpine